version: '3.8'

services:
  html-cleaner:
    container_name: html-cleaner-server
    image: html-cleaner-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    restart: always
    volumes:
      - ./logs:/app/logs
